spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ursur?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ods030207_
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  com:
    amazonaws:
      util:
        EC2MetadataUtils: error
  org.hibernate.type: trace

ISBNApi:
  certKey: b0322f25a2f5642f7ad7398814af16c6aee9c394ae6f9cb5503d5b337e0c30a3

Email:
  fromEmail: minsu9254@gmail.com
  password: nzklwflnsvxfdmux

Phone:
  apiKey: NCSJ0CMODEPTHI8N
  apiSecret: LES6I7QDGSUUDRDS5TEP8P2C8BFDSZFY
  fromNumber: 010-5407-9254

cloud:
  aws:
    credentials:
      access-key: AKIARHOALEMMLG6F4VPN
      secret-key: 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
    s3:
      bucket: elasticbeanstalk-ap-northeast-2-084692116248
    region:
      static: ap-northeast-2
    stack:
      auto: false

#server:
#  port: 5000